{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "pve-dev-private-repo-secret",
    "namespace": "argocd",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "pve-dev-private-repo-secret",
        "namespace": "argocd",
        "creationTimestamp": null,
        "labels": {
          "argocd.argoproj.io/secret-type": "repository"
        },
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "sshPrivateKey": "AgA/yrX9uIXhjJi2ZCUEqXqdpYbnEMcbR6rv2xO8tvT/Y7Z0aAQy9VoUEQKyBemp1wegg8pyeStixFpV5gPYeHCU0NQpP/F6xbb+Stve1hUSpqxXWJ8hFabT0Ysrkm8h54P3CP33gYuHQ0OcG+hJY6+KbNEmYadF6yP7p4if4eYAd4BWvSfdhQS8RTsV65E3Mrgm2Z6Us8SBu6Y/9gnQBFwxZTpHPDUI8a5vR9QdlkFgYGabbhQA2hVkWmJ5HEK/+2iWM2eECUOL4IxwOwNdqRzf4LODEBk/yLvosU6JordPLkZwoOThtz9E8LSHtbcoAvdmXhKL7uyUg0RTa4wWEkBrVQBcXevQbb6elwlHA2mxEick8sQQJjaP1yVjIsM+Lks3aq9mkN3Lhc0oS4IKFQQ3cBnt5UoKla3VUzwr0MyHxtjgt0omfSKNt7jojVJv2f8nttJftHTVjWBc8+SNY1OozYGJ9T6gI8hkO7bYyRi06FVhu1MOOZqo9NHSYImCIxuotSZaRHSIK0mL0KKdArXKPRutIS69jidNTL4BzWCZLE5wBzQukCO+uvM6FkpOi2/kYbYyvGQGhffjMssttzR9pRT4RKBK6PWIxcq5DzKfOqHAAkwHVhH6pH/iFAxZFKWgsLgXnVEvalOZaOOctY7rUA21WtZFWT6OVLtq3o/bmWoOK0m9K5kwhLlXLNIfIDkEqKVd08fK40k4XHK0csspRjqr3olGHlHwUHCgbyLVNMnTvnQrX+GkTTvt1qzRY5mtNG9y0Zisz8Ji0GyJbh1qo2JnUMld+BQlXOmWRoK7defTSW/q0+sndwmfv7d6IEeZkR0OlL1fUwNOhJ/z7n5ApW+NWHb5dcZ1DrZWQFUid3U468XEu9q/ztFrMbbZPO2U2yzOD36H3jP2x5Zv5dCd2yWMuGZeV9ZtraNoo9EdXZXSKKeGuJ9+n+YFkUXIXB0AkHDsVlEBHWcEZ+0mXNC3qXXrKH5XmOEeiqrJRAgF7FuKoCQG+E9xjrcYAj/KQx7c9WOZSqGBvfROmmZpMmu9+sFOD5Q/hdgTdYzya17/eT8dVr5GUzl+CIHx2ksnFHoX7UUjHzNm2qL1MnqNfhBCLzY6JDtKzBwADz2zAjCBhhr2jORxwv+G1A6nywYRVwKEs9P3na11LH5d5fb4kaZyeSgq3XFbdNegDD8zks0WppczeCvzNV07MIt0IvO2DUaJsi4TK7CIPG3y4IrB4sNWVWlEHOTQyNVdsGY=",
      "type": "AgCm1SFSQuGEbp7GxgqfzgH7uSerp8T80X5nuSOZclOsMdR1l0qg89hHs/KVI9ZfcK1Jpr67r0n8A7JxhSPd3fUPbJvtZhOLuSAiAJ5Gdv/d8SWLl/s1pbm4wd/6yNPQEokpsne6TkcLFYKfue2CtJ/qTZ4Q8xMDhqPWkjJbmhHsbI1eXJ9tYp+HvTtU+y+pPGX850fC8nJZgTABfHaHv59l1t+B5ikeWzMeY0UFHwM6StsjQaKo4grE5z8uZay27SsvuNyglYCYJREcp0426Q5NzImUi2PogpNn6xpWaV1N5Fhsz2g6SU2oxOczS4RxTqEdE2OSNlzq3D9++Q7qAUyhxY5tWV7SQA4KddyhEq+d7BAk9vvV9Z+wrAJgGV/ldDV9vD/C3Z25FeX/nkv4tMv8uIvAfdjURZC/YLdN35UZfILTCwFs0+nHmbLIWySZ6t1Qy1cYxGxpKlEsZ1mEwQfY9+OosWBXQxigrhiljYHIKb9vRzBOL5qkKkGh6NdD8LjSOP4W1FdM3u8N/WSwoEslJfIx+B6ub9+OAU+GjT1EQz3RZ32PFO+sg8ufmrUfQcuGmJ0u8Ef5aQe7ZQkTQulrWD2ROyx66iE3Q7RgWE+0xdjOUV+2w3nLEJS80xVYb6D2kGAyLSc7kBGbY50sN8LquHi33iVIvf5//9Lrv0+G6RBuFxzaU69X0ytquCtY0rCw83c=",
      "url": "AgBKC3FfB6WWkkKUoTv2AVObJm01EEbCcNLYoququpuHM6oJl+7sNjMC+jdRyqf5ic9AANKZfecnCl362vlkEqlNKQRaa50PZGwUuWydrzJ8c1le8yhkeJYeWxAki4ji5aUwMJxxElR+1sZMgDw3GF25dzQQE9IJ7H2Go1W6jDvFpXhle6zVkoDkWt4OxS5irvq5RW+vOexBRa2u/TD52e9CMX7WMDA+npyOkBUxUl4/4Yljq4p9vZ1Bptf3QDoULRhTEr12+NRnFucpY2Tt5Ezcf6om5wHXdDKkXtAU4+QdJa32clgJydYeYjy+YUZ/Efib4ytthFJlJjpu4gAOs9xE2JAoJAZeOM+2/pZ892LpiYyv/QYzmjxxUfo0CZ1NM0fBK0393rpNYJTykVih0O4TAI3XoEjGZU46NqG39r912tWNe8YNgKgwp5afPTmOGrBXpqp9K/V6LrzdfImswP1LRzFQKCQc4pF42M14wVG7CEDPJdquoli/PAKy2b9HCcppDgDfOWOv+zRrP9E7KSq8i4Xhwx6wS0ej2ER39FvbW1fMYeFVmB1rQHCy7X/2itEGBlyKiQRlToIVEmNrLnFwJoDH0vXC773rmwc6QGW14WxdRLnR+5xSTnzHrWlNmMU/irTsiAE5Wjl/+hPCUW91BEwFruff38TcqgvFMxaur4bcfgAe2g+08DgTSBr5xL2Aj1zDaj7+wo/TDadF/wwhBAImO9Bpo/sHOQOWsUXmk+NDWH5dtg=="
    }
  }
}
