{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "pve-dev-private-repo-secret",
    "namespace": "argocd",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "pve-dev-private-repo-secret",
        "namespace": "argocd",
        "creationTimestamp": null,
        "labels": {
          "argocd.argoproj.io/secret-type": "repository"
        },
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "sshPrivateKey": "AgAXRlRCPwuAVPG18iXO2/jkyzKUiQyP4NfU9BcDIULDaw13KE5MxQSdpOxa/S7fw3wzHBEye4mWNw1yk6BNO6EDFtjzm03bzS3AgejbD4nGQg5aTiWkRCdKGo++0VbAEP/KiWi8oTLjjQRSmDWuuQEPPoJHFPE6sVOoiY1FxfeF22ARQ62O4UhdMYJoufwKxuHNaU4eF2gzHJXYVzVU6Qmr8IUfZ1SAdeP82RNNGnp+rQ1hVzJBf2f8IzF6/kUlKhmLQbRFlw+rRUUgF4/nwg70r2i/mI6QrrEVur7HwVqgIB5Pu1ahcZZjRk14SaK/4w4FcKxdq/4GZiAV2HRFfX4ZmAeHZNfA52lgN7/IP+k3H20cIgRvAfHBuNEbtGkMSQRwic4TVEFU+aRGXAGJ2AzC6w+kAlDl6NXJ8sjGM+jLfV6PSflhhTj+IV//OMSq8jg7yArgDJIfhqOnwc1vWe8/AnJTOqmDepuTZg33321F09f8jWeTWP3EaLCupbbsF1pYLQUK3PNo51IjCyRKBn7I0u/gJyGVgkh8MCN5+8t455MPRwZCYieiB44InpjUHBSSNrYEkrWkSlJ+/Rl9k6j6OucwUSXba1uvO0w76mZE56q5Lalg6NP5ZmI5hDlp0/bmIEEiWEKK5KPwBG4gSds4wt2xVAMqLhQNeirP/WWLy83RtLXlU0Q3ow13OVln0sJ+c3al2aA/nSLDXMxDPdFbkt9TTiYPIqoJIftgXJJPx4zxNXdDU1hAdnBVEM1WjZwbpvw3PWM1FHhrWw83LX5kwoYPZEhSWKoJfHYnL6+OleBAJsuykACUyi/lByzJRCS8vDmrjEhoQlsHozaLbg7FdKlLJ5Wppp29YvOvxmDA+3sNIkAFHGT5dWe3k3K6Id/SUwuXUFLgxtTlnbqToE4Ii50YCX13JNQXeb93pGrg1GoR5Ou7w+LVJf7UOow5is56KTCE7ffZ9+BEnlfvP9EN+S4yQuk/k0x4b7z0XNSppJUIFfjsOySrpzjil4tgipfnNsjoVrU9NSIEgGw4eoENfHvi/Pu33dLgLcUWXvDi7RcDE0S6OUwmxbyjDiMUI8GvaocFsKyZlh+24bwCOwhyHkcPkfk45s5iHVKKg+1ja3tY/TrGiXfJGOxIHwT6EoTobmsOxIxdNEbbxaEHpVkcRO77+pih2mN4CUosJCnMqAlzYqKorqhc4fkJXBeH4sHzyxDKzCDRpB07bLanptdEyKlhbDiD9jU1/HU=",
      "type": "AgCWviEsU45OhZSSt9GgUBSRZOE3Dtl96rq81r9rUBsOhdgsVKZwYO7xvqlP9zQ2wyK4f3EDp5dlOp8dhlN5pxCJsEarshTuqnyHpYvm3xg2L1giEjoaGmXBxUThHrk01rUpLZ52pjzdFmgW4KCr7qaGRHkbH0Jz8JOBuXyfIt198Wke3/08tv6OmCMrHh3zzg6YiSq0dx8U2DuHpd1F8YtFoF53UBqSjdlX4OjKTuPAqCifCq24ItJ5Bmn06oFE6hB11bKa3QhqoNZTtqQK/C/as7OT1V+IGsa1eEsF7awp2a5HKZr2jE0cM0lXS5vFbujzpvt6hl/C+4JPwZ0UuB0RW1IHEJeFf5NDq+/3e5TfxXx9pK9off4qvipG0dOLHUu2/4V1zZDk8iqesKKYchY2MijHgn2GGisrscRuCBmmgvCgGjiwvD7jCFsY955BQSAv+HPBs1kqSE0JgglwSBSFQIRTMq2GEhUdRBU2iXbRhGlT/LeZlbox9+IJ6pY/Bhv2MRdN8kMJ28iaZdfGwzZfbqr0GsfRncTS+B8esNvLjWbFfC17CEablNuWLxcGPwc2qKA+F7PN99uSK2hWRwhfQb0Dmv10gQ4plNa332kxQb0SrIk0gv/p9fgIVaNJLDa4CKlqNfZ/ddkdprykooqRAnBbFqcTgXSx00qXHT3zHGEciaMg4CJv0+JQ5t0+052gtk0=",
      "url": "AgAsavq70/DOSSoWc3WBhZ97akRIrq9NR7IHCpz903fTvPQ/TZQYdQ+vMQOoeBgYqX+MExmw2qKjk3jRGKxXLp5CmDPn25Gm1kSSYJahRWxgNw6NceoAy5S/Vk3P/o16Jjp9QhSxIbe3KsXFtaj4f32Rp3VX/jiQAJmrulnoEFlKXMvjSiHeI60gCUeq3ayXXxZ02cWptI+9I/f3qh0TY2DLQotr/o1Y+jJHw3nTtHBI2g5wyweiZtt7G1fF0TXuPtJOC+CcKgKmfgXv6+O7JipKO2kWcSUDUgm1vRvyWCr89Yi1cxiJSAJ5xdk6b9zWJwW3BkEhZpXRYz+5iFLJGbYNLgokFg1IXjVqTwA4g4MqbpE6EQvgVtZSgRtImV1dj1hI/ALJNg5zk3Rwx/jC0CNdlUzb9yozoRHLb6Ectg+hQLTbPM3kWO0zOCqjBUyLNUZdm0EezlNvx4npBPfl5EB7YQdlMyvBGxQ6NrX3P3BoSsIRx1iaHV1sz8RM3+XEbbzCMq19aCxNN7lt3ZPnx619K4xNfXp4KA9T93KVGwY7JREaVa7gpa8TdCIGetTqVUy7SHfmjRm4iTv7xIb36I8get63s7V7gpOafOVqbUE7UbMQ9yhp9gywPgqGt1RltpbzaP1KsEsHgGea4hAPcGhY0Ycn3bvjnW36icrwGAnZIm0S9Wpe/eoCcIM9k3yScAnW05i3A47Aa/UAEdWrlR9NXrABnD3elqDxk//3qNb/4kpsHEkmEw=="
    }
  }
}
