---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin_password: AgCQzV29wGOfupVAhU4RAEb+hsot4sDs+F2S3BVbFdT87wqbfVBx5L9wPjA6vfjZ2pivDxa9rnaKV1oWn3l9qYwr7tZAgxunLwrX1wisNqDrplS1GsiCJ++TlOO3iYt3d8HqNf0eeNMRERaU531p5buWI/vGMRfpcHJB59Gh0ZSAq8IjAuiXKxUVfXm4MIwCs/LvK2P5bPH8J1jDEzK6QJ5w7ZbND7z8tgH2bkcv9J5VmspKKntL+lreqS7+1fu8cu4PnAJDxTMXsZkoeKR0sd8ImryJ7HNCJM1tMBtPafFn0gYW3Lto7F7UDLdO2ZPcel0kpDHdHBKhQYTMyJmV4o7uCWoFbAU8NguPLAHbOKCsGFVa4VUneTDSbbFpGMNGwE3T2UMsdov/6Fuawd638YeSMuKIPRPI3R1bpTmXgG33ux8dDxF87ZJltVgSgp1mL4AjaRPbVVq+0RWY3FonMqKFQW1Yo/brfJ5I80fDRoitXaF8LZs3puwtOCkbOr0nYH76BuX1MxreH7elJYSVbKsOsdhlUDKU4/30GPKDWVqB1Ejl12DRHzODZYeCIMHj7728SYgD/By9oylTF092tYX1KROWNXKtbhkCEdoUVjCXvRRCmCw/BfF6nTOGmkvmcwFilqsyoPXspqjnF2P20Lm6jTzVfuraHVTDcdQjfZfcFl7Wnz1CKGj391T6VeKmRfC+0zKxCKdRN5ctqQ+xfA==
    admin_user: AgATNDH612prXOCL1rNNJYXudZF05sW7MEYLAKLdBcz3iIlXwHcJxZS3yeAGsQV83PlcnTnzIzYn81teP6Dgutji7XDLi4dco+8G4BuMER9UTWh1JyQ7UvV1nMcBB40LrvWVZL0ceOqWhPO+gd+2D+hz/6rtOEyqa13PS29jUmN2kZnYSoYjSQ/OCuE1aJ5CsQx1MI/sKVd3RJ8LKl/B+LtBiyuzM1e7CbXPMOZ9wLsrvFUrVNk7ui/48/+q8gY3lFeApa14ikLealONMWcfmtgoHQAbVpTrbocAuVouHeR/vKnCZauaPdnn0bFbO2Y4RcPzgnPVnFNuyrg69+U0NDHGPWgBfpLM423gXq9K3JG7RCyPRuPc81QF3h8gZoV3LOKWX1waT7zE4gACt/TXoJmHTTDfBL8h3MCxMnq0IPqM+rr3/IO1yWHRL7QSdp31D5QjjMkM5N9OEcSoeAjxYlGiwNvEj9k8TgIFm+qbq/s0CfuY6Z4uZtN1Ow+myJ5CAFIG9mootwMDpPH11LzS6KMy+DQYIRME45z9MXTyFQ9Agn98qtSJHZlhvpU3UsJz0q2A7k46Xk6PZUlkSsACEsEVW9SUT3c1ptO3CSJREyGY78hdVONYjm6BXkmaR3pAdSlW1DWgKDUnmN63LiIxZgPUAFnzF3qlf9kenzCOAd6IIHnt9imOIXJsrDHj56cTxr2u65Mm+WE=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
