---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBtdK2aEHAOFcwyFt+hFt4rYeDpc+mooB4ew3Yh1Vsv/aQYSuQCrM1alYYE+KaCg4DMFn3FRsMNXsjXPuIypuEP/Kb/GmEdXIHcOpk9faFqTuzpl8mMVu3HssNBrFq0A0GJWsQuckQfELJgqOOVqml4eYQpyqcgyaXFt94N0CtSfewkdyEBkpqCD5R/R4eOQH/mFe8T1CKl8RxEv73pH1iDqF2L89Hs3JplO2G6u25nu+D8jssl44Ow+CZkOgRzpYZojnJQ/AH1Mg7L8+U3CZtznnhuNHrRvL6w1Sr6hgL25TZiwxCEFK3z/89kzMsBUH7AJor+Ur0502d7QEBvK/Br63zRz4mxgJLfBhJfpLsaIu7NlV/Jw3Z/GHPSBScZlWEcHkkuboDhKobCW0lDOiZ6gRBVydwI3riXv4HyxmCZDFDxxzBwhuubtaYNR+/ntj7alDt/zJ571CODlUA9YeOmU+U8+SGxEVXC+qNOa/+t/TaZYZ1xSsK9lXW0OunhmJpM3qKKjOMBXO1PCXKBi2LdC054NokSBa9WKcVMYQaiu9KFWDztRpMzHUXi1egoubCN7pVR2UVguOBDWyFPrM4mokQzYHtU8xf+ZwpUJFPkYnszxQ8hT2h9BT7nvj+YC1C+yCSQ1ECY9GRbkpIuEcVgumzf5URlfFdr4vQ+MctzO0tS2Bm22SeTDwbrD9Er6kBfZBGnYixDAXkdkmUsQg==
    admin-user: AgAFzbIBbMmpXrATvRXUmO9ovXFi5m6QGJM65CgEOXx4rwNPof1TptTlQDafMrMMmkP6YfwjxnDpdqMx3Xqzu2G6zokNXB86orP3d9+U/yTooRc9OAkIn6iCFrfHCjH+eaFN1tSCW2GglVNIMgLz/lKt7bRAWHu79T+N6QEwTdJszuwyJx8GljEw5o7k0L5+FldIplT72mbB/XV0zs2eQ/CLJoiBZka5sYtqmh7McwqoT/F2sU1y8RG1jXji9dklA6Xv7Llq1tQgpuQ/ZzRMXWvRdQoWyzz1D65qXMisHLu4WPFIrqdHuTaOrO9AlORatFLYv195s8RwFKuwqxNnvcWQovOeykA5MdyU+qOkVz0ETbStejFn1K49vAu0nEFoQEgR+eqMwwE750u/QVLwhm0CEFqEhO2KwkQsI/KVHeDCiMLHocCQig0wYBtzyMpxDxs8ZFLlOu5TIta6xWT2KYyNMhS/vXOJklHzZbbMLrML0wpFIWlaId0k4n+ZYtHleXVTG1w/pw5qThSXK36NX1ZgSMyyFU7weYIdAv9kiOfYtPXDhaHHo/YGlA9oS483xuqwoRB3dkfLd7veH+qCPIxUAqhGWy2yDGkkyMX86jttluXod9MXo2LJXFdzGomZ58KzoRVmcViPzCiMWkxZrKbU1sv+zBjdispWH81ggHs0RTtHxSmBTHyzzlWyH8Ob9QgPxBoyumM=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
