{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-admin-credentials",
    "namespace": "monitoring",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-admin-credentials",
        "namespace": "monitoring",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "admin-password": "AgCt/TW7i8QIj6RmWQZkDgeZKC62AmQqJRVp8NJCLD9ajgFvskcMgY+Ki88WhjvQGfiAuJ/a+AVq4tMYGl5wuyfuh/pBFG9Rr41zgcWH+hlbP0oKI02XEypgw7OAL8GpDH5G6W7o3Uz5Pa+fnKS2TDix1xcj5YB41Q6abRBDWletchX0SCQd8yEgWBYBLK7Pq3iy05gE0ePPQcB/E3azUd6FpGXFULegTcXFDLdqLsJYS10GqR+JG67zyhpyr0ZVlnOQY46S6aOVUN2hTYR90OxYNnyRr0Uo4zV+DvoxEx8l4zzcxgqIL4ywqGI4F2bRevDJktAL6uk0J9TQNaBfDIVx3qlDAKa+6uYslmsMFPuOD17y6WI6Apg3R1TOC+638nhXfJfyVbBWJT9dPXe2EQqgEd+RYXsXlcQ+u5Ool/EZ35MPWDkeftwNsfbaLNJ3jwZXbKyK8rPvM8HXkdww+uWvFs9VEHrhJ6/3bj7dAKveZlIvzhbXDjrEtgaZiVQINFmwtYyrDJp6a7Fd37WIRs+NL/vQmVIFELC5pQrRnlaKYXr7OrsNh6mTphj6Sl6waAPWWUbnbuey1gkAPw5HtN1y8zmAiNSSVvUpDAe74f+qjKGmYSOzs6fsk65gxHuvx03AXnTDo02YPkPz31n9srOfO7Ds4tIzjl++vGLajnYPW9AmAqAx4v2FpMcHqTF4dIJyfaRrjTp1KC2X3Ix/QA==",
      "admin-user": "AgCRcORg/BOXZfDUb5WUoqn0UBYWkXfAonVO68EdKNrQzDWrBEH4uCmCmpv73a4w4xE1MmpeuiBroCL/vmp/JfhmVzfSQ7CPYGguoK7VR6NkBEGF6ESvnHO3ZSZ7WfDvzhcX48qN49F42Zdghk0bjsL+onjPJooEojYbtg2N0Bgy36JwZU4vbla8CWsU1J7WPNls+ZecoySi25XWmVMRJ4LskevLv/LKQIYmOEV8rkl/7gLw3+MgkPJT7qgtgVlMydC/kO5qdEbuc92LnLRGu767FJe4hnOE5/WDvQ415rniKDsZRvZWbT3rWqpYiJLT1Aw2wg4KnaNwJ8Z2uqRB4ZIAuWfjr/mimKPrH0VV27TeFtV3Et7HnGkvL5y6yi3ZLLUGt/iQuX8gPbdV+PLm4qYryGG4cp2hua938IC4UkhdZhVGOJWo88ihg+NodVkqdUfwQOm8NympQ+bVuOGyY/Q4XIjUDMrFf5q9xx8Fzv4itIe/Eqt3fEIRJExC2AEPJWdSH9or9PZRz6uRwL8/RZKxM3MoNnwRpujncj/maNYuqhH/odxJvdNp+q0S3U+GKi1PV6cWlhPtPDCdjXxXK32K9D0C7sQeRW0gTzh1OORrJkZCw7K5AHrFWJ8qYZsTNjIeu+3qi6i2npPmaiZkysnXybBjJxfTT4DiaDbh7ZCqpNxPjWyq+gHQfxpZNiGK7niae3c/ZiU="
    }
  }
}
