apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mongodb-operator

patches:
  - target:
      kind: Deployment
      name: mongodb-kubernetes-operator
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.azure.com/scalesetpriority: spot
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: "kubernetes.azure.com/scalesetpriority"
            operator: "Equal"
            value: "spot"
            effect: "NoSchedule"
