apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-infrastructure-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: sealed-secrets
            repoURL: https://bitnami-labs.github.io/sealed-secrets
            chart: sealed-secrets
            version: "2.17.4"
            namespace: kube-system

          - name: cnpg-operator
            repoURL: https://cloudnative-pg.github.io/charts
            chart: cloudnative-pg
            version: "0.26.0"
            namespace: cnpg-system

          - name: kube-prometheus-stack
            repoURL: https://prometheus-community.github.io/helm-charts
            chart: kube-prometheus-stack
            version: "77.14.0"
            namespace: monitoring
            valueFiles:
              - infrastructure/overlays/development/kps-values.yaml

  template:
    metadata:
      name: '{{ .name }}'
      namespace: argocd
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      source:
        repoURL: '{{ .repoURL }}'
        chart: '{{ .chart }}'
        targetRevision: '{{ .version }}'
        helm:
          {{- if .valueFiles }}
          valueFiles:
          {{- range .valueFiles }}
            - {{ . }}
          {{- end }}
          {{- end }}
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [ "CreateNamespace=true", "ServerSideApply=true" ]
