# This ApplicationSet creates the Helm-based infrastructure apps for the dev cluster
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-dev-infrastructure
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: cert-manager-dev
          repoURL: https://charts.jetstack.io
          chart: cert-manager
          targetRevision: v1.17.2
          namespace: cert-manager
          helmValues: |
            installCRDs: true
        - name: ingress-nginx-dev
          repoURL: https://kubernetes.github.io/ingress-nginx
          chart: ingress-nginx
          targetRevision: 4.12.2
          namespace: ingress-nginx
          helmValues: |
            controller:
              replicaCount: 1
              nodeSelector:
                kubernetes.io/arch: "amd64"
              service:
                type: NodePort
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{targetRevision}}'
        helm:
          values: '{{helmValues}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
---
# This Application creates the self-signed issuer for the dev cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-cluster-issuers-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: main
    path: infrastructure/overlays/development # We will create this path next
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true