apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-ssd-pv-k3s-cp1
spec:
  capacity:
    storage: 120Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  local:
    path: /mnt/local-ssd/k8s-volumes
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-cp1
