apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  labels:
    app: elasticsearch
type: Opaque
stringData:
  username: elastic
  password: "{{ randAlphaNum 16 }}"  # This will generate a random password using Helm template function
