apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: litellm
  namespace: litellm
  labels:
    app.kubernetes.io/name: litellm
    release: home-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
      app.kubernetes.io/component: proxy
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
