apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # This section configures the repository connection.
  # We will switch this to HTTPS in the next step.
  repositories: |
    - url: https://github.com/HowDiggy/k8s-gitops.git
      name: home-dev-repo
      type: git
      project: default

  resource.customizations: |
    # Fix for "Too long" error on CRDs
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreAnnotations:
      - kubectl.kubernetes.io/last-applied-configuration

    # Ignore status field for all resources
    all:
      ignoreResourceUpdates: |
        jsonPointers:
        - /status

    # Specific ignore rules per resource kind
    ConfigMap:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."cluster-autoscaler.kubernetes.io/last-updated"
        - .metadata.annotations."control-plane.alpha.kubernetes.io/leader"
    Endpoints:
      ignoreResourceUpdates: |
        jsonPointers:
        - /metadata
        - /subsets
    apps/ReplicaSet:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."deployment.kubernetes.io/desired-replicas"
        - .metadata.annotations."deployment.kubernetes.io/max-replicas"
        - .metadata.annotations."rollout.argoproj.io/desired-replicas"
    argoproj.io/Application:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."notified.notifications.argoproj.io"
        - .metadata.annotations."argocd.argoproj.io/refresh"
        - .metadata.annotations."argocd.argoproj.io/hydrate"
        - .operation
    argoproj.io/Rollout:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."notified.notifications.argoproj.io"
    autoscaling/HorizontalPodAutoscaler:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."autoscaling.alpha.kubernetes.io/behavior"
        - .metadata.annotations."autoscaling.alpha.kubernetes.io/conditions"
        - .metadata.annotations."autoscaling.alpha.kubernetes.io/metrics"
        - .metadata.annotations."autoscaling.alpha.kubernetes.io/current-metrics"
    discovery.k8s.io/EndpointSlice:
      ignoreResourceUpdates: |
        jsonPointers:
        - /metadata
        - /endpoints
        - /ports

  resource.exclusions: |
    # (Your exclusions section remains unchanged)
    - apiGroups: ['']
      kinds: ['Endpoints']
      clusters: ['*']
    - apiGroups: ['discovery.k8s.io']
      kinds: ['EndpointSlice']
      clusters: ['*']
    - apiGroups: ['coordination.k8s.io']
      kinds: ['Lease']
      clusters: ['*']
    # ... and so on ...