apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  ssh.knownhosts: |
    # github.com:22 SSH-2.0-550beff
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    # github.com:22 SSH-2.0-cb24e083
    # github.com:22 SSH-2.0-550beff
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
    # github.com:22 SSH-2.0-550beff
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    # github.com:22 SSH-2.0-550beff
  repositories: |
    - url: git@github.com:HowDiggy/k8s-gitops.git
      type: git
      project: default
      sshPrivateKeySecret:
        name: private-repo-secret
        key: sshPrivateKey

  resource.customizations: |
    # Fix for "Too long" error on CRDs
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreAnnotations:
      - kubectl.kubernetes.io/last-applied-configuration

    # Ignore status field for all resources
    all:
      ignoreResourceUpdates: |
        jsonPointers:
        - /status

    # Specific ignore rules per resource kind
    ConfigMap:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."cluster-autoscaler.kubernetes.io/last-updated"
        - .metadata.annotations."control-plane.alpha.kubernetes.io/leader"
    Endpoints:
      ignoreResourceUpdates: |
        jsonPointers:
        - /metadata
        - /subsets
    apps/ReplicaSet:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."deployment.kubernetes.io/desired-replicas"
        - .metadata.annotations."deployment.kubernetes.io/max-replicas"
        - .metadata.annotations."rollout.argoproj.io/desired-replicas"
    argoproj.io/Application:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."notified.notifications.argoproj.io"
        - .metadata.annotations."argocd.argoproj.io/refresh"
        - .metadata.annotations."argocd.argoproj.io/hydrate"
        - .operation
    argoproj.io/Rollout:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."notified.notifications.argoproj.io"
    autoscaling/HorizontalPodAutoscaler:
      ignoreResourceUpdates: |
        jqPathExpressions:
        - .metadata.annotations."autoscaling.alpha.kubernetes.io/behavior"
        - .metadata.annotations."autoscaling.alpha.kubernetes.io/conditions"
        - .metadata.annotations."autoscaling.alpha.kubernetes.io/metrics"
        - .metadata.annotations."autoscaling.alpha.kubernetes.io/current-metrics"
    discovery.k8s.io/EndpointSlice:
      ignoreResourceUpdates: |
        jsonPointers:
        - /metadata
        - /endpoints
        - /ports

  resource.exclusions: |
    # (Your exclusions section remains unchanged)
    - apiGroups: ['']
      kinds: ['Endpoints']
      clusters: ['*']
    - apiGroups: ['discovery.k8s.io']
      kinds: ['EndpointSlice']
      clusters: ['*']
    - apiGroups: ['coordination.k8s.io']
      kinds: ['Lease']
      clusters: ['*']
    # ... and so on ...