apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-rbac-cm-es
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: argocd-rbac-cm
    template:
      type: ConfigMap
      data:
        policy.default: role:readonly
        policy.csv: |
          g, {{ .ARGOCD_ADMIN_USER }}, role:admin
  data:
    - secretKey: ARGOCD_ADMIN_USER
      remoteRef:
        key: ARGOCD_ADMIN_USER
