# infrastructure/base/argocd/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - service.yaml
  - argocd-cm-es.yaml
  - argocd-rbac-cm-es.yaml
  - security.yaml