apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 45.27.2
    helm:
      values: |
        # Enable CRD management to get a fresh installation
        prometheusOperator:
          manageCrds: true
        
        # Use unique names to avoid any potential conflicts
        nameOverride: "monitor"
        fullnameOverride: "monitor"
        
        # Use ephemeral storage for simplicity
        prometheus:
          prometheusSpec:
            storageSpec:
              emptyDir: {}
            retention: 15d
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                cpu: 1000m
                memory: 2Gi
                
        alertmanager:
          alertmanagerSpec:
            storage:
              emptyDir: {}
        
        # Simplify Grafana configuration
        grafana:
          persistence:
            enabled: false
          adminPassword: prom-operator
        
        # Ensure node-exporter can run on all nodes
        prometheus-node-exporter:
          tolerations:
          - operator: "Exists"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
