apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: talos-prom-auth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: talos-prom-auth
    creationPolicy: Owner
  data:
    - secretKey: CF_ACCESS_CLIENT_ID
      remoteRef:
        key: CF_ACCESS_CLIENT_ID
    - secretKey: CF_ACCESS_CLIENT_SECRET
      remoteRef:
        key: CF_ACCESS_CLIENT_SECRET
