apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.homelab.local
