apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/qdrant

patches:
  - target:
      kind: ExternalSecret
      name: qdrant-api-key
    patch: |-
      - op: replace
        path: /spec/secretStoreRef/name
        value: azure-keyvault
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: QDRANT-API-KEY
