apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cloudflared-token
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-backend
  target:
    name: cloudflared-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: CLOUDFLARE_TUNNEL_TOKEN
