config:
  cluster:
    enabled: false

apiKey:
  valueFrom:
    secretKeyRef:
      name: qdrant-api-key
      key: api-key

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

persistence:
  size: 20Gi
  # storageClassName: oci-bv # Uses default cluster storage class if omitted