apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-apps-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: prod-apps-root
    app.kubernetes.io/part-of: applications
spec:
  project: default
  source:
    repoURL: git@github.com:HowDiggy/k8s-gitops.git
    targetRevision: main
    path: apps/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
