# clusters/oci-prod/infra.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: main
    # Point to the Kustomize overlay for production infrastructure
    path: infrastructure/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: {} # Keep the manual sync policy for production