apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-paulojauregui-com
  namespace: argocd
  labels:
    app.kubernetes.io/name: dev-app-paulojauregui-com
    app.kubernetes.io/part-of: applications
  annotations:
    argocd.argoproj.io/kustomize-version: v5.7.1
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: HEAD
    path: apps/overlays/development/paulojauregui-com
  destination:
    server: https://talos-api.paulojauregui.com
    namespace: paulojauregui-com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
