# infrastructure/base/postgresql/postgresql-cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: signconnect-db-cluster
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
  superuserSecret:
    name: postgres-superuser-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      shared_preload_libraries: 'pg_stat_statements,pgaudit,pg_vector'
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_vector;