apiVersion: apps/v1
kind: Deployment
metadata:
  name: paulojauregui-com
  namespace: websites
  labels:
    app: paulojauregui-com
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paulojauregui-com
  template:
    metadata:
      labels:
        app: paulojauregui-com
    spec:
      containers:
      - name: paulojauregui-com
        image: ghcr.io/howdiggy/paulojauregui-com:c58ed194f060e63b34268f76962e1aa4ac96fed9
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
