apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-admin-password
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      templateFrom:
        - literal: |
            accounts.{{ .ARGOCD_ADMIN_USER }}.password: {{ .ARGOCD_ADMIN_PASSWORD_HASH }}
          target: Data
  data:
    - secretKey: ARGOCD_ADMIN_USER
      remoteRef:
        key: ARGOCD_ADMIN_USER
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ARGOCD_ADMIN_PASSWORD_HASH
      remoteRef:
        key: ARGOCD_ADMIN_PASSWORD_HASH
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
