# infrastructure/base/cert-manager/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - letsencrypt-issuers.yaml
  - sealed-cloudflare-token.yaml
  - application.yaml