---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCGpe5RsPwMsMHt0strryCkJs3caOA3TokSJs5zsWCO6/8L/KhLK4DO1YjzjbAVaWWWgHQlP5ivmr+p37HT6sfJBirU4xb+YnI1qCEyGY/h9h5Ybe56fmd+eYV6gkxn1aza9EDNdxWgAzaxMuONK8dVndf49lBt8AeAmAiOoft3SjnbqT83/jknYjtvfPJYd8uLzCRcLXVQfF7eTap52qCE4vf9JSUeOA/WJiYys5KBCMHNWHZOckiFrzEshhHTmRKh4ULzaXWA2gxBft/TIJTtCNJGwiLcbcYwQZCOgy+awpxenj11JW2hztKo+hjCgq3Rx8JduPcxI40pIsy+t3r9X+mIHnWMnBmkKp/pSIp/gvEs5MVuVY3lfrBKFWZZRJBFCLQTvnHgaMZb/GMk4Hr/DX/ck/J9FGobgx5GDjHsN0w0LRTTaa+qOM/0oMtYz3+TRxed4B49ER0xnCYrEM0uDBUUdVv5fd9mKPWn123rqyQCt0V0eROlkJgI0sAdTJ0md2aZWrSVfQ62HwN+xVa0BYSHfXrUy2skiuHDbZm1E0dao5zAZGuXcf48GlxoBYuWUTS65hshzJoMClXWgRTUq28Pbxpx5FxSxhkle4wCE/JSh/TR51qAX0lpYfnMzUsoM+akeYHd25SIsXO3wLWPHYjk2FYdNQQVDe4XRhPcA8sEqCJvzIlFyElrR+2+DgsBHBzBhKlrhXdmyQizTydRDf4JycByAAuX6g913zRN+m/rYQ9H+JBm
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
