---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC1cymgE7Z86jagiJA9LaQ2EBP7jisGUPVLLge5yGiD+zqUrmOyAgSdirdyYb+dmUrqe8T9WCeXLR0umGNZGw373jrV4ZbaxyabA+kZCblYv6cS2kEkvoZVjc1i/mhKthTQWMmKQ7MrtAd5li9ysdt7uyHSNPNzw6csqTKP2cGLfEb/uinMCAsX+T4WpNtixFIFwS9ZAgfZYczebfs9BKg2m326G8DE/mx8NFflu+E7sbZw8WqQmdCzto1nXSVmQbUcbaXS+UELtR3KRfp2N+I5ZIB733a1hzxR1/91iOC9n2GpqCmtlLc/iEJHFroNDDPQmseu8WgdZDJtrNN+zrLZRRQLvjTJSw4b4WtUxzCA/8yYXU+3621gsi+vvbrLAnb9KPimKhlASy9F/A/5sV9/Hw6Q5uAO8DubQ8PH8G75ZUy/w7h72ZOO8ouM6rCR7YAW1nXX1ZZG4l3BHwzAq8wkk0VDL2KmRw8nzns/nltAQtpplJI6/iK0yqISygAXuqwf/22CVYoUvun/yuTh+fLG3CYedRh1y7Cy7cmBxlX017p0dMX1j8lpOwZRfJGq45Q/p7B97hQI4P+cRepo1PmfvF7Vbm4hzC5zxgs+ti/knHWdnxcc9UQ0Afrc3XfL1dD71CcE3tZi4qdiNIIHvJwAumPEwvawjVAVuvuD+qJ/97DrrNlb1XiiYWw+vInpHsh/EIL0OT+xzDnM4KnWZ6emFBkB3D1gRfmdb+4aB0Z9SwhzCLGG0XFi
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
