{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token-secret",
    "namespace": "cert-manager",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token-secret",
        "namespace": "cert-manager",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "api-token": "AgA4S1lbh/FBktfGY3houDN8LaVFO8W1m0H9Zs5iC9k2wBl8Sqd77PqKbMrwKqql/WsHKVB2NKEeGC4UubKS9DvqQBGhhNhI2UswRa5oLukyFkXGzekjJPCQy584tdYojOYj+72aYR48SAgI52m1Fma1WPaDrvz9Kgijr/UvjBp3+nOZ+RptW7ohVlpkkgzHFyHVgyZdxqIScuaOfozJWBVSgg35piG9WhXyQJ3VqKuyLJulIeCIfvs2PkzdXBLt18JgeTtOdHSbp0QGyVeY/DfwgolDGFey1X6H16tLB097CPk+IWPKjbh2kUbQov2JzKrr6ariLOf0dVVA5M7ye9rIxFvz3mluJ4hp0L9bkobCAQB7MV507h9bMoExh416tv5ag4Va5cqPVALM4j9BzWZpvHw5B4QxhZ8X0b8ENVsvDOC5tkK/Lam3VY5E94Su9NNLOyF4uIIDpOVLJEkE/8mIf6Vf1TLkPi27x6XaRh6PAh+txpu4Ol0gOidDtGwEblqGTaHPeIYQdgyjHOiS+C2jVW7LA/089yimZL1/ouXnqNQkQ6d5152q44XtyPKL5Lgct0P/Ip4lnAAgU3fV4OgidRFEXk89YleXUthQDyDMU6aTjUdQxQr935LOTzvLPSQarzrzshpGRLqWf+0QATxBiA2AU+yld+KC6hS4obPpVBfWLLxWpxMW4bfJR1kqkLDdYihtOjYtlWGqppUvI/CxXHBQvPNJNie+L+xBXLMowcyYM7hLiJVp"
    }
  }
}
