apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-prod-infra-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: azure-prod-infra-root
    app.kubernetes.io/part-of: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: feat/azure-migration
    path: infrastructure/overlays/azure
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
