apiVersion: apps/v1
kind: Deployment
metadata:
  name: paulojauregui-com
  namespace: paulojauregui-com
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.azure.com/scalesetpriority: spot
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
