# This defines an ArgoCD Application resource for Tekton CI
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Name of the application in ArgoCD
  name: tekton-pipelines
  # The application is created in the argocd namespace
  namespace: argocd
spec:
  # The ArgoCD project this application belongs to
  project: default
  
  # Source configuration - where to get the Tekton Helm chart from
  source:
    # The Helm repository URL for Tekton
    repoURL: https://cdfoundation.github.io/tekton-helm-chart/
    # The specific chart to install
    chart: tekton-pipeline
    # The version of the chart to use - pinning ensures reproducible deployments
    targetRevision: 0.5.0
    
    # Helm-specific configuration
    helm:
      values: |
        # Enable Role-Based Access Control for Tekton
        rbac:
          create: true
        
        # Configuration for the Tekton pipeline components
        tekton-pipelines:
          # Resource allocation for Tekton components
          resources:
            # Minimum resources guaranteed
            requests:
              cpu: 100m       # 0.1 CPU cores
              memory: 128Mi   # 128 Megabytes of memory
            # Maximum resources Tekton can use
            limits:
              cpu: 500m       # 0.5 CPU cores
              memory: 512Mi   # 512 Megabytes of memory
  
  # Destination defines where in the cluster this application will be deployed
  destination:
    # The Kubernetes API server URL - this refers to the current cluster
    server: https://kubernetes.default.svc
    # The namespace where all Tekton components will be installed
    namespace: tekton-pipelines
  
  # SyncPolicy defines how ArgoCD should keep the application in sync
  syncPolicy:
    # Automated sync configuration
    automated:
      # Remove resources that no longer exist in the source
      prune: true
      # Automatically fix any drift between desired and actual state
      selfHeal: true
    # Additional sync options
    syncOptions:
    # Automatically create the destination namespace if it doesn't exist
    - CreateNamespace=true
