apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config-pvc
  namespace: calibre-web
  labels:
    app.kubernetes.io/name: calibre-web
    app.kubernetes.io/component: config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-books-pvc
  namespace: calibre-web
  labels:
    app.kubernetes.io/name: calibre-web
    app.kubernetes.io/component: library
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 50Gi
