apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-calibre-web
  namespace: argocd
  labels:
    app.kubernetes.io/name: dev-app-calibre-web
    app.kubernetes.io/part-of: applications
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: main
    path: apps/overlays/home/calibre-web
  destination:
    server: https://kubernetes.default.svc
    namespace: calibre-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
