apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-all-components # Name for this parent/grouping app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:HowDiggy/k8s-gitops.git # Your Git repo
    path: oke/cluster-addons/cert-manager         # <<< Directory it will manage
    targetRevision: main
    # Instruct Argo CD to look for YAML/JSON/Helm files in this path
    directory:
      recurse: false # We only want it to look at files directly in this path for now
  destination:
    server: https://kubernetes.default.svc
    # This parent app creates resources (other Argo Apps, ClusterIssuers)
    # which will have their own namespaces or be cluster-scoped.
    # 'argocd' is a fine namespace for this parent app CR itself.
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # For any namespaces defined by child apps
