apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
type: Opaque
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiMzVkOWUxMWFiZTJmMjdlMmVjMzU1NDkzY2Y4NDMwODMiLCJUdW5uZWxTZWNyZXQiOiJWT0l1L0QxSzFvNHNyZUVycWFBcjE1RUFoZ2V0cHd4amFDektTQmltNUJzPSIsIlR1bm5lbElEIjoiODE2Njk2MmEtMzcyOC00YTVlLWI5OTktNjFhOWNmYWM3NDkzIiwiRW5kcG9pbnQiOiIifQ==
