apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-agent-principal
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: argocd-agent-principal
        image: ghcr.io/argoproj-labs/argocd-agent-principal:latest
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/arch: arm64
