# Production values for Single Node / Low Resource availability
crds:
  enabled: true

grafana:
  replicas: 1
  # Need to use the secret we created via ESO for the admin user
  admin:
    existingSecret: grafana-admin-credentials

prometheus:
  prometheusSpec:
    replicas: 1
    
alertmanager:
  alertmanagerSpec:
    replicas: 1
