# infrastructure/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Include the base applications
  - ../../base/ingress-nginx
  - ../../base/cert-manager
  - ../../base/argocd

patches:
  # Apply the production-specific patch for ingress-nginx
  - path: ingress-nginx-patch.yaml
    target:
      kind: Application
      name: ingress-nginx
  - path: argocd-agent-principal-image.yaml
    target:
      kind: Deployment
      name: argocd-agent-principal