apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: talos-prom-auth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: talos-prom-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CF_ACCESS_CLIENT_ID: "{{ .CF_ACCESS_CLIENT_ID | replace \"CF-Access-Client-Id: \" \"\" | trim }}"
        CF_ACCESS_CLIENT_SECRET: "{{ .CF_ACCESS_CLIENT_SECRET | replace \"CF-Access-Client-Secret: \" \"\" | trim }}"
  data:
    - secretKey: CF_ACCESS_CLIENT_ID
      remoteRef:
        key: CF_ACCESS_CLIENT_ID
    - secretKey: CF_ACCESS_CLIENT_SECRET
      remoteRef:
        key: CF_ACCESS_CLIENT_SECRET
