apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: infrastructure
spec:
  project: default
  sources:
    - repoURL: https://qdrant.to/helm
      chart: qdrant
      targetRevision: "1.17.1"
      helm:
        valueFiles:
          - $values/infrastructure/base/qdrant/values.yaml
          - $values/infrastructure/overlays/azure/qdrant-values.yaml
    - repoURL: https://github.com/HowDiggy/k8s-gitops.git
      targetRevision: main
      path: infrastructure/overlays/azure/qdrant
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
