master:
  nodeSelector: |
    kubernetes.azure.com/scalesetpriority: spot
  tolerations: |
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
volume:
  nodeSelector: |
    kubernetes.azure.com/scalesetpriority: spot
  tolerations: |
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
filer:
  nodeSelector: |
    kubernetes.azure.com/scalesetpriority: spot
  tolerations: |
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
s3:
  nodeSelector: |
    kubernetes.azure.com/scalesetpriority: spot
  tolerations: |
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
