apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/seaweedfs

patches:
  - target:
      kind: ExternalSecret
      name: seaweedfs-s3-config
    patch: |-
      - op: replace
        path: /spec/secretStoreRef/name
        value: azure-keyvault
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: SEAWEEDFS-S3-ACCESS-KEY
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: SEAWEEDFS-S3-SECRET-KEY
  - path: spot-patch.yaml
    target:
      kind: StatefulSet
