apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-queue-data-0
  labels:
    app: logstash
    volume: queue-data-0
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  local:
    path: /data/logstash/queue-data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-worker0  # Choose a worker node
