apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paulojauregui-com # Name of this Argo CD Application
  namespace: argocd      # Argo CD applications live in the argocd namespace
  finalizers:
    # The default behaviour is to leave resources in the cluster when an Application is deleted.
    # Add this finalizer to delete resources when this Application is deleted.
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Argo CD project
  source:
    repoURL: git@github.com:HowDiggy/k8s-gitops.git # Your GitOps repository URL
    path: oke/apps/paulojauregui-com                # Path to your website's manifests
    targetRevision: main                            # Or your main branch name (e.g., main, master)
  destination:
    server: https://kubernetes.default.svc # Deploy to the same cluster where Argo CD is running
    # The namespace where the resources from the 'path' should be deployed.
    # Even though your manifests specify 'paulojauregui-com',
    # this reinforces it for Argo CD.
    namespace: paulojauregui-com
  syncPolicy:
    automated:
      prune: true    # Delete resources that are no longer defined in Git
      selfHeal: true # Automatically sync if the live state drifts from Git
    syncOptions:
    # This allows Argo CD to create the 'paulojauregui-com' namespace if it doesn't exist.
    # It's a good practice even if you have a 00-namespace.yaml.
    - CreateNamespace=true
    # Ensures that resources are applied in a specific order if needed, respecting health checks.
    # For simple apps like this, it might not be strictly necessary but is good practice.
    - ApplyOutOfSyncOnly=true

