# apps/base/signconnect/01-backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signconnect-backend
  labels:
    app: signconnect-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signconnect-backend
  template:
    metadata:
      labels:
        app: signconnect-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/howdiggy/signconnect-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            # Map keys from the CNPG secret to the variable names your app expects
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  name: signconnect-db-credentials
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: signconnect-db-credentials
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: signconnect-db-credentials
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: signconnect-db-credentials
                  key: dbname
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: signconnect-db-credentials
                  key: password
            # Set non-secret config
            - name: SENTRY_ENVIRONMENT
              value: "development"
          envFrom:
            # This loads the rest of your secrets (API keys, etc.)
            - secretRef:
                name: signconnect-backend-secret
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"