# apps/base/signconnect/01-backend-deployment.yaml
# This is an updated version of your existing file.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: signconnect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: signconnect-backend
  template:
    metadata:
      labels:
        app: signconnect-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/howdiggy/signconnect-backend:latest
        ports:
        - containerPort: 8000
        # This new 'envFrom' block tells the container to load all key-value
        # pairs from the 'backend-secret' as environment variables.
        envFrom:
        - secretRef:
            name: backend-secret