# apps/base/signconnect/02-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: signconnect-backend-svc
spec:
  selector:
    app: signconnect-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000