# apps/base/signconnect/03-frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signconnect-frontend
  labels:
    app: signconnect-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signconnect-frontend
  template:
    metadata:
      labels:
        app: signconnect-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/howdiggy/signconnect-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            # This is not a secret and is only used by the Nginx proxy config if needed.
            # It's safe to keep, but is not part of the current problem.
            - name: VITE_API_BASE_URL
              value: "/api"
          # --- REMOVED `envFrom` and the specific `valueFrom` for the API key ---
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"