# apps/base/signconnect/04-frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: signconnect-frontend-svc
spec:
  selector:
    app: signconnect-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80