# apps/base/signconnect/05-backend-secret.yaml
# This is a new file you need to create.
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: signconnect
type: Opaque
# Note: The values here are base64 encoded.
# You must replace these with the base64 encoded versions of your actual secrets.
# To encode a value on your Mac, run: echo -n 'your-secret-value' | base64
data:
  # Required by Pydantic
  GEMINI_API_KEY: QUl6YVN5Qm1rN1hFTy16WmExVnJHOVhVeG1Sc3dEZk5SNktCNTBJ # Replace with your encoded key
  FIREBASE_CLIENT_API_KEY: QUl6YVN5QlNxRjBkdVl6ZFZHQ2ZKQzFZT2RGcWMyT0dpQlVLcFRn # Replace with your encoded key
  POSTGRES_SERVER: cG9zdGdyZXMtc2VydmljZQ== # This is the base64 encoded value of "postgres-service"
  POSTGRES_USER: bXl1c2Vy # Replace with your encoded user
  POSTGRES_PASSWORD: bXlwYXNzd29yZA== # Replace with your encoded password
  POSTGRES_DB: c2lnbmNvbm5lY3RfZGI= # Replace with your encoded DB name

  # Sentry Configuration
  SENTRY_DSN: aHR0cHM6Ly9hMTQ1MGRlMGQwZmExNTlhZTcyOWQ4ZTBmY2Y1YWMzYkBvNDUwOTg0OTIyNDA4NTUwNC5pbmdlc3QudXMuc2VudHJ5LmlvLzQ1MDk4NDkyMjU3MjM5MDU= # Replace with your encoded Sentry DSN
  SENTRY_ENVIRONMENT: ZGV2ZWxvcG1lbnQ= # "development"