# apps/base/signconnect/07-postgres-deployment.yaml
# This is a new file that defines the PostgreSQL deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: signconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: ankane/pgvector:latest # The same image from docker-compose
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: backend-secret # Reuse the same secret for DB credentials
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc