crds:
  enabled: true

grafana:
  enabled: false
  persistence:
    enabled: false
  admin:
    existingSecret: grafana-admin-credentials

prometheus:
  ingress:
    enabled: false

alertmanager:
  ingress:
    enabled: false

nodeExporter:
  enabled: true

defaultRules:
  rules:
    node: true

