apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  source:
    helm:
      values: |
        crds:
          enabled: true

        grafana:
          persistence:
            enabled: false
          admin:
            existingSecret: grafana-admin-credentials
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.sprout.localdomain

        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.sprout.localdomain

        alertmanager:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - alertmanager.sprout.localdomain

        nodeExporter:
          enabled: true

        defaultRules:
          rules:
            node: true

