apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
  labels:
    app.kubernetes.io/name: kubevirt
    app.kubernetes.io/part-of: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: feat/networking-lab
    path: infrastructure/base/kubevirt
  destination:
    server: https://talos-api.paulojauregui.com
    namespace: kubevirt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
