apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/sealed-secrets.yaml
  - ../../apps/cnpg-operator.yaml
  - ../../apps/kube-prometheus-stack.yaml
  - ../../apps/nvidia-device-plugin.yaml

patches:
  - path: kps-values-patch.yaml
    target:
      kind: Application
      name: kube-prometheus-stack
      namespace: argocd

