# infrastructure/overlays/home-dev/mongodb-operator.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: mongodb-operator
    app.kubernetes.io/part-of: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://mongodb.github.io/helm-charts
    chart: community-operator
    targetRevision: "0.10.0"
    helm:
      parameters:
        - name: operator.watchNamespace
          value: "*"
  destination:
    server: https://talos-api.paulojauregui.com
    namespace: mongodb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
