apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: main
    path: infrastructure/base/qdrant
    kustomize:
      enableHelm: true
  destination:
    server: https://talos-api.paulojauregui.com
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true