---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCw2eOiuL38iiJQqoj6ibrF2RQ+62oayYMZnieIfz+LGzUTo5J3HwxYBovYv7HYncsAzWELi50pDdFDHHTc4Pie1EOY1AidkSNxaaJI4PJxQBMvlliQHuDXsCTw5kkaJdUmE0QH7VnNeZlbot1J2JR2TmfC4w6WCgNx1waf9v5lK5ScjUk/agsu5iPgjckBtPNflwVIB6n8d+xdyEfYIn2WJwo9XlPx5DRMynJpX/qMvL3r1IfTs2TZEJUbmDN5TZQX4MiBfkkFts2ueJoTEcobxIHvdnvsTlHi8Pfx2CYmHVCn1sGDPgog46RkColWEpe7ObNqleQpmvATR4Q/81fLbqHEkB9p0bOpBP6mDCzQDF0Hu52pccBhWIAue1rmudj8D1Q6JJzLwyyksn8DecW3asxkq5RzXVLZhWpiLoTsjDIPFAiPvgXL0Qa/mHnEswpoaNzc/GL5UWsDPLKI3/NxrWM2nctD27+tn65IIVjdQIGef6KpKclKdR7+29G02ZNU2FQQFDhdjSjosft9syxToE37EW7sTQ3a65w0OIzVP+UUubafdNEqTAvWbulz8WNJP7Npw4VU8fwf9nfQ5zKsmHVKK8+eNzw3zopiqnNCY2Pt7pOmZ2XcSWr4aXMGEipyRezFds2K8C5neeI7vQwFyI5JRMLcUqDcq8onFCNfoFYUBcLMkTIV5CT6m9cQ5yii0MVSmifRCvyCWwX7vg==
    admin-user: AgBX1eGW4tY1HY2JPT/A45ioMmY1HCBg5wVSlUEv3yXUj/SJuYkOe+atCMfnZWz7Nhgx2xBXPPdr3UzApeFUx0nz/k78b4kPwMM0LN2nDmT6xc7ZPmSt8x7AJ7elfslxflsNloi4l7DUAE5rDFPImtt2clNGf6UAUV6v4AKEfPT5inevzD0AZ23wNqnsjoTUXAkVHrKwpASKk3k2tnLksbzEKsionwvRlI9et3+PDCq8smEFnQA+kbK6WUl4sE/9V1XyD17I292eu5Sk6/98hVohxcuPEh8C6CVo6iX/jXiKtIx4MJUpItX/spSrg0c/e+lwO9fOU8tOaa1s3OH2PQkoUVx5E0MhOxnEbc33pOtmpnK1McC4MPYB/IH3tO5eJ7ByLsdGwtjs8Q2kM19Q9iz9kUaPgGHkWTAdlNgPgIQG8wMQ74oLzRlnr1Cd/Y4B3OropAZQUyc806lSCUuaPo+vPMX5p8J5G2Nl5qBuq9aA8DRaHR3Dl5yJ44z8IbX1PcQ6lilFzpflqKz4ADYqMLM51cirIyX0ZjP7T/Nfblu6j21h7a2ock1WWhaD8++I+tbb4mZfsI6HkErsdeyk5qO0stwIcRKZKMTGpCxUUbSt/AZ+q5i/3nwkZvHe8xpVXmKtF/GwR998tMh2xPHJM3P6SwdN6ZsrosJcFFqTQATVjkJDIRc8a27xDAQQr6ACobtbfEB+dO4=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
