---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC4YIpuUNsrI+pnHPUCqrd/inTVbjGqemrcuSl6aw3cv+jABiMXT39OG0v5om8LUYNFAY3Zugxh6u6P6mfySpS03PI9bj4fvGw9YzP6wXg7jNrfIZXDXOgYrxxUiLSkK12SKnAEbYCHjbMyJMnPmAyHtJ3HbASXxKaBlYHTBX4ATqy7qn7XB54Fh7TrK4r4u3QEIayhtFujq0hmeqrENOjWLcI6B8gygifvxJkPVM+13wWqUVptIMzIkBQP0vBrVdgx1h7YbEhELgjJ20JKPruVV1FTWvIwpMGNvS1gRrvs3g3zXJojHLt8z7VON8f6h7A/sEnq3/MAxrhhvcvyzlKQ8helRPvi7sSIse+ruU+bdenAEQ2m05nt6ml3lHHNxWSr/U96OfE5ceQ2sATkAqrlZfWR9aSs2z7Z1CZs4m/SEat/rvaMNCqPkmthCu9C/MVPdk/WJMyYnC3kYzGJj7VHMs7P6HnjFh+pu8qiSzJ+DFZc+3bXCAkpk3YkJjJ2iDwDcBL+2FW7eXa7gMfXC2S+aT7PZUWG2QW7+h1z9Fw13XasOcSoUFOzrD+N5/rucnyh2DjgsUMG6N0Ymtacans6Vpz4pUXBVBezYVNBQhVoNhI1EMFB/cJXGU9zRLJLkECSuFgqNxvNbdMpNNA9VjXhsrrZL96BLMI6j04UN2ymiMoGqnYBT6p/VbuRu38KLV0AEvGoPG8kXSlKGQuRHw==
    admin-user: AgAW0MLcwOB8cHjulPYcF70ZmbBQ3Cldl58ttswSmThpTrWKUa+gbY1S2c4A9UDNHRUNm9iHxwuNNPbteDDLPdtHjZPZ71CIxTtxBiubr6SD+mSMu8grVPBKAN2RMVRjWJ9BqKH2KNIsPVjHjryR3XokDxVViZn3tDYDreBFrAs2SVVJMWw9NMhESZFjTk0ILTlBpt9zL1WfIpwklIYl+6YKzAepH1kPAst8psgOPT/s4ox+q/QABKOabACLcmCCjOS9JwLtKh4Ttqy0OW7wNUE3tv3356sHeVywtgX7Bke4vThPySbTpEVNIp0XwDZvW67ab2dE+YzQyUvXxSkv3hw/I4BjBpC6ZMU95UER2UDOeZIWDMfFoV7XuHSxjhrJL+Phl25lfoAjoCRtwJe67OjTCIYR4zFaFq8YEHBxwfBA340LZTayU5LX8RoKr3JKFX3e/BrMaNrsAANVLhZe3A/p5LmGKLzO6+WWySunOb9tQZFPyqmQlAa48NiDpCCC/6wDKSqEzf62nH3FBFNHCT7NM0Q9Af8nIl7DH+32jdgfOeT7KTAzf5TNQ3OWA7hFFLNNZLTs3Q8rm7wOefNYiSHRYcBsYjnTshbga4wopDrU7YDNCIUC53hs98EOOy2arbO3H9ucDpCiJJ7sOaSf7wK05XdLIcXjmr9Wto8c1lKWuFHc9GueUQ++T/noGHJdkaR0ImhsFD4=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
