apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mongodb-cluster
  - pdb.yaml

patches:
  - path: replica-patch.yaml
  - path: spot-node-patch.yaml
  - target:
      kind: ExternalSecret
      name: mongodb-admin-credentials
    patch: |-
      - op: replace
        path: /spec/secretStoreRef/name
        value: azure-keyvault
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: MONGODB-ADMIN-PASSWORD
