apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: git@github.com:HowDiggy/k8s-gitops.git
      type: git
      sshPrivateKeySecret:
        name: private-repo-secret
        key: sshPrivateKey