# infrastructure/overlays/staging/ingress-nginx-patch.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.12.2
      helm:
        valueFiles:
          - $values/infrastructure/overlays/staging/ingress-nginx-values.yaml
    - repoURL: https://github.com/HowDiggy/k8s-gitops.git
      targetRevision: HEAD
      ref: values