# infrastructure/overlays/staging/ingress-nginx-patch.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  source:
    helm:
      values: |
        controller:
          replicaCount: 1
          nodeSelector:
            kubernetes.io/arch: "amd64"
          admissionWebhooks:
            patch:
              nodeSelector:
                kubernetes.io/arch: "amd64"