webhook:
  enable: true

certManager:
  enable: true
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
    group: cert-manager.io

spark:
  jobNamespaces:
    - spark-operator
  rbac:
    create: true

controller:
  rbac:
    create: true
