# infrastructure/base/sealed-secrets/sealed-secrets-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    # Deploy this in an early wave to ensure it's ready for other apps
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: "2.17.4"
  destination:
    server: https://kubernetes.default.svc
    # It's best practice to install it in the kube-system namespace
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # We don't need CreateNamespace=true as kube-system already exists
      - ServerSideApply=true