apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager # This is the ArgoCD app that deploys the Helm chart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 'v1.17.2' # Or your confirmed latest v1.17.x
    helm:
      values: |
        installCRDs: true

        controller:
          nodeSelector:
            kubernetes.io/arch: "arm64"

        webhook:
          nodeSelector:
            kubernetes.io/arch: "arm64"

        cainjector:
          nodeSelector:
            kubernetes.io/arch: "arm64"

        # The startupapicheck is a Job that runs. It also needs to be scheduled on arm64.
        # Its values path might be slightly different, but this is a common way.
        # If it errors, we might need to check the chart's values.yaml for 'startupapicheck' specifically.
        startupapicheck:
          nodeSelector:
            kubernetes.io/arch: "arm64"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
