apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: observability
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: inter-node
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-api
  namespace: observability
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    name: rest
