apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-0
  labels:
    app: elasticsearch
    volume: data-0
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  local:
    path: /data/elasticsearch/data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-worker0  # Specify the node where this local volume is available
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-1
  labels:
    app: elasticsearch
    volume: data-1
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  local:
    path: /data/elasticsearch/data-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-worker1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-2
  labels:
    app: elasticsearch
    volume: data-2
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  local:
    path: /data/elasticsearch/data-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-worker2
