apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: observability
data:
  elasticsearch.yml: |-
    cluster.name: k8s-logs
    node.name: ${HOSTNAME}
    network.host: 0.0.0.0
    discovery.seed_hosts: ["elasticsearch-0.elasticsearch", "elasticsearch-1.elasticsearch", "elasticsearch-2.elasticsearch"]
    cluster.initial_master_nodes: ["elasticsearch-0", "elasticsearch-1", "elasticsearch-2"]
    bootstrap.memory_lock: false
    xpack.security.enabled: false
    xpack.monitoring.collection.enabled: true

    
    # Enable snapshot repository
    path.repo: ["/usr/share/elasticsearch/backup"]
