apiVersion: batch/v1
kind: CronJob
metadata:
  name: elasticsearch-backup
  namespace: observability
spec:
  schedule: "0 1 * * *"  # Run at 1 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-backup
            image: curlimages/curl:7.83.1
            command:
            - /bin/sh
            - -c
            - |
              # Register repository if it doesn't exist
              curl -X PUT "elasticsearch:9200/_snapshot/backup_repository" -H 'Content-Type: application/json' -d'
              {
                "type": "fs",
                "settings": {
                  "location": "/usr/share/elasticsearch/backup"
                }
              }'
              
              # Create snapshot with date-based name
              SNAPSHOT_NAME="snapshot_$(date +%Y%m%d)"
              curl -X PUT "elasticsearch:9200/_snapshot/backup_repository/$SNAPSHOT_NAME" -H 'Content-Type: application/json' -d'
              {
                "indices": "*",
                "ignore_unavailable": true,
                "include_global_state": true
              }'
          restartPolicy: OnFailure
