# Define an ArgoCD Application resource for managing all other applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This is the name of our root application
  name: root-application
  # It's created in the argocd namespace where the ArgoCD controller runs
  namespace: argocd
spec:
  # The ArgoCD project to use (default is fine for most cases)
  project: default
  
  # Source defines where ArgoCD should look for application definitions
  source:
    # This must be your actual GitHub repository URL - using the same one from your demo-app
    repoURL: git@github.com:HowDiggy/k8s-gitops.git
    # Using the main branch, just like your demo-app
    targetRevision: main
    # This path should contain all your application definitions
    path: apps
    
    # The directory configuration should be nested under source, not under spec
    directory:
      recurse: true
      jsonnet:
        tlas:
        - name: ""
          value: ""
  
  # Destination defines where this application will run
  destination:
    # This points to your current Kubernetes cluster
    server: https://kubernetes.default.svc
    # The argocd namespace is where the application controller runs
    namespace: argocd
  
  # SyncPolicy controls how ArgoCD keeps your applications in sync
  syncPolicy:
    # Automated sync makes ArgoCD automatically apply changes when it detects them
    automated:
      # Enabling prune will remove resources that are no longer defined in Git
      prune: true
      # Self-healing automatically fixes drift between desired and actual state
      selfHeal: true
