apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signconnect-backend-secret
  namespace: signconnect
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: signconnect-backend-secret
  data:
    - secretKey: FIREBASE_CLIENT_API_KEY
      remoteRef:
        key: SIGNCONNECT_FIREBASE_CLIENT_API_KEY
    - secretKey: FIREBASE_SERVICE_ACCOUNT_JSON
      remoteRef:
        key: SIGNCONNECT_FIREBASE_SERVICE_ACCOUNT_JSON
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: SIGNCONNECT_GEMINI_API_KEY
    - secretKey: SENTRY_DSN
      remoteRef:
        key: SIGNCONNECT_SENTRY_DSN
