apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-secrets
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: mlflow-secrets
    template:
      type: Opaque
  data:
    - secretKey: MLFLOW_DB_PASSWORD
      remoteRef:
        key: MLFLOW_DB_PASSWORD
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: MINIO_ROOT_PASSWORD
    - secretKey: MLFLOW_ADMIN_PASSWORD
      remoteRef:
        key: MLFLOW_ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-db-credentials
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: mlflow-db-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "mlflow_user"
        password: "{{ .MLFLOW_DB_PASSWORD }}"
  data:
    - secretKey: MLFLOW_DB_PASSWORD
      remoteRef:
        key: MLFLOW_DB_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-auth-config
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: mlflow-auth-config
    template:
      type: Opaque
      data:
        basic_auth.ini: |
          [mlflow]
          default_permission = READ
          database_uri = postgresql://mlflow_user:{{ .MLFLOW_DB_PASSWORD }}@mlflow-db-rw:5432/mlflow_auth
          admin_username = jaupau
          admin_password = {{ .MLFLOW_ADMIN_PASSWORD }}
  data:
    - secretKey: MLFLOW_DB_PASSWORD
      remoteRef:
        key: MLFLOW_DB_PASSWORD
    - secretKey: MLFLOW_ADMIN_PASSWORD
      remoteRef:
        key: MLFLOW_ADMIN_PASSWORD
