apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-talos
  namespace: argocd
  labels:
    app.kubernetes.io/name: cloudflare-talos
    app.kubernetes.io/part-of: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: main
    path: infrastructure/base/cloudflare-talos
  destination:
    server: https://talos-api.paulojauregui.com
    namespace: cloudflare
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
