# apps/overlays/development/signconnect/ingress.yaml
# This patch adds an Ingress to expose the frontend service on your local cluster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signconnect-ingress
  namespace: signconnect
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: signconnect.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
