# apps/overlays/development/signconnect/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# This points to the base manifests we created in the last step
resources:
  - ../../../base/signconnect

# These are the patches we will apply to the base
patches:
  - path: replica-count.yaml
  - path: ingress.yaml
  