# apps/overlays/development/signconnect/replica-count.yaml
# This patch targets the backend deployment specifically
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: signconnect # Added namespace
spec:
  replicas: 1
---
# This patch targets the frontend deployment specifically
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: signconnect # Added namespace
spec:
  replicas: 1