apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signconnect-db-app
  namespace: signconnect
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: signconnect-db-app
  data:
    - secretKey: dbname
      remoteRef:
        key: SIGNCONNECT_DB_NAME
    - secretKey: host
      remoteRef:
        key: SIGNCONNECT_DB_HOST
    - secretKey: password
      remoteRef:
        key: SIGNCONNECT_DB_PASSWORD
    - secretKey: port
      remoteRef:
        key: SIGNCONNECT_DB_PORT
    - secretKey: sslmode
      remoteRef:
        key: SIGNCONNECT_DB_SSLMODE
    - secretKey: user
      remoteRef:
        key: SIGNCONNECT_DB_USER
