apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-cluster-issuers
  namespace: argocd
  labels:
    app.kubernetes.io/name: cluster-issuers
    app.kubernetes.io/part-of: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: HEAD
    path: infrastructure/base/cert-manager-issuers
  destination:
    server: https://talos-api.paulojauregui.com
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
