apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doppler-cluster-store
  namespace: argocd
  labels:
    app.kubernetes.io/name: cluster-store
    app.kubernetes.io/part-of: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/HowDiggy/k8s-gitops.git
    targetRevision: main
    path: infrastructure/base/cluster-store
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
