apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: infrastructure
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      targetRevision: 3.12.2
      helm:
        valueFiles:
          - $values/infrastructure/overlays/home/metrics-server-values.yaml
    - repoURL: https://github.com/HowDiggy/k8s-gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/HowDiggy/k8s-gitops.git
      targetRevision: HEAD
      path: infrastructure/base/metrics-server
  destination:
    server: https://talos-api.paulojauregui.com
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
