apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-db-credentials
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: immich-db-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "immich"
        password: "{{ .IMMICH_DB_PASSWORD }}"
  data:
    - secretKey: IMMICH_DB_PASSWORD
      remoteRef:
        key: IMMICH_DB_PASSWORD
