apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-nfs-pv
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: library
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.13.82
    path: /volume1/Cloudy
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: library
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-library-nfs-pv
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache-pvc
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: machine-learning
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10Gi
